### ISSUE TITLE
Plugin ne charge plus depuis Regadata

### ISSUE THREAD

**Issue by dragful** [devpotion/windy-plugin-osc-rdr#1]
Bonjour,

Le plugin semble se lancer mais ne charge plus les données de regadata.
est-ce un problème ponctuel ? ou l'organisateur a-t-il fait objection ?

merci

**Comment by devpotion** [comment]
Hello, the issue seems to be linked with adblock. I have to try to change the backend URL Thatcher contains the word track.

As a workaround, you can diable adblock on windy.

Bonjour, le problème semble venir d'adblock. Je vais essayé de contourner en changeant l'adresse du backend qui contient le mot track.

Pour le moment vous pouvez désactiver adblock sur windy.

**Comment by dragful** [comment]
Hey
thanks for the quick answer !
This was indeed ublock origin which was guilty. it works well with adblocker such as Privacybadger.
thanks
